language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
    composer self-update
install:
  - composer install --dev
script:
  - vendor/bin/phpunit tests/
  - vendor/bin/phpcs src/ --standard=ruleset.xml
matrix:
  allow_failures:
    - php: '7.0'
    - php: hhvm
    - php: nightly
