language: php
php:
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
before_install:
    composer self-update
install:
  - composer install --dev
script:
  - vendor/bin/phpunit tests/
matrix:
  allow_failures:
    - php: '7.0'
    - php: hhvm
    - php: nightly
notifications:
  slack: hulk-php:EqjiAncwk58CQeh9O50JEMQE
